# Generated by Django 4.2.7 on 2023-11-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_alter_borrowing_expected_return_date"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="borrowing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="borrowings.borrowing",
            ),
            preserve_default=False,
        ),
    ]
