# Generated by Django 4.2.7 on 2023-11-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_borrowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
