# Generated by Django 4.2.7 on 2023-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0014_alter_borrowing_expected_return_date"),
        ("order", "0003_order_is_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="borrowing",
        ),
        migrations.AddField(
            model_name="order",
            name="borrowings",
            field=models.ManyToManyField(to="borrowings.borrowing"),
        ),
    ]
