# Generated by Django 4.2.7 on 2023-11-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("FINE", "Fine"), ("PAYMENT", "Payment")],
                        max_length=20,
                    ),
                ),
                ("session_url", models.URLField(max_length=1023, unique=True)),
                ("session_id", models.CharField(max_length=150, unique=True)),
                (
                    "money_to_pay",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Borrowing total price",
                    ),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
        ),
    ]
