# Generated by Django 4.2.7 on 2023-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="type_status",
        ),
    ]
