# Generated by Django 4.2.7 on 2023-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63)),
                ("description", models.TextField(max_length=255)),
                (
                    "daily_annual_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Daily annual fee in $USD",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(blank=True, null=True, to="books.author"),
                ),
                (
                    "genres",
                    models.ManyToManyField(blank=True, null=True, to="books.genre"),
                ),
            ],
        ),
    ]
