# Generated by Django 4.2.7 on 2023-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_annual_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Daily annual fee"
            ),
        ),
    ]
