# Generated by Django 4.2.7 on 2023-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_daily_annual_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(blank=True, to="books.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="daily_annual_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=7,
                verbose_name="Daily annual fee",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, to="books.genre"),
        ),
    ]
