# Generated by Django 4.2.7 on 2023-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_remove_author_first_name_remove_author_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_annual_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=7,
                verbose_name="Daily annual fee",
            ),
        ),
    ]
