# Generated by Django 4.2.7 on 2023-11-26 18:58

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_daily_annual_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.book_directory_path
            ),
        ),
    ]
